"""Initial migration

Revision ID: 7c94cd772413
Revises: b57569be4069
Create Date: 2024-01-12 13:10:08.522565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c94cd772413'
down_revision: Union[str, None] = 'b57569be4069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_recipe', sa.String(), nullable=False),
    sa.Column('text_preview', sa.String(), nullable=False),
    sa.Column('text_post', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('text_comment', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('recipe')
    # ### end Alembic commands ###
