version: "3"

services:
  generate:
    image: generate_app
    build:
      context: .
    command: "gunicorn core.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000


  prometheus:
     image: prom/prometheus:v2.43.0
     container_name: prometheus
     volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
       - prometheusdata:/prometheus
     restart: unless-stopped
     ports:
       - 9090:9090

  grafana:
     image: grafana/grafana:9.4.7
     container_name: grafana
     volumes:
       - grafanadata:/var/lib/grafana
     restart: unless-stopped
     ports:
       - 3000:3000
volumes:
  grafanadata:
  prometheusdata: